version: '3'

services:
  web:
    build: .
    image: django-vite-example
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  vite:
    build: .
    image: django-vite-example
    command: npm run dev
    volumes:
      - .:/code
    ports:
      - "3000:3000"
