# Generated by Django 4.1 on 2023-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
