# Generated by Django 4.1 on 2023-03-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-user',)},
        ),
    ]
