# Generated by Django 4.1.7 on 2023-03-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0006_post_created_at_post_likes_post_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
