# Generated by Django 4.1.7 on 2023-03-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0002_post_likes_post_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
