# Generated by Django 4.1.7 on 2023-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0009_rename_comment_comment_body_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='user_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
