# Generated by Django 4.1 on 2023-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0010_post_admin_deleted_post_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
