# Generated by Django 4.1.5 on 2023-03-06 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 17, 37, 11, 926850, tzinfo=datetime.timezone.utc)),
        ),
    ]
