# Generated by Django 4.1 on 2023-03-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
    ]
