name: Vue CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # don't fail the entire matrix on failure
      max-parallel: 4
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        node-version: [16.x, 18.x, 20.x]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        npm ci
        npm run build --if-present
        python manage.py collectstatic --noinput

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: cypress-io/github-action@v5
      with:
        start: python manage.py runserver