name: Vue CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Set Environment
      run: |
        export APP_ENV=testing
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: cypress-io/github-action@v5
      with:
        build: npm run build
        start: npm run dev