name: Vue CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:

    runs-on: ubuntu-latest
    strategy:
      # don't fail the entire matrix on failure
      max-parallel: 4
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4] # Uses 2 parallel instances
        # run copies of the current job in parallel
        node-version: [16.x, 18.x, 20.x]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        npm ci
        npm run build --if-present
        python manage.py collectstatic --noinput

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: cypress-io/github-action@v5
      with:
        record: true
        parallel: true
        start: python manage.py runserver
      env:
        # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
        # in GitHub repo → Settings → Secrets → Actions
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
        # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}